version: '3.3'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_HOST: db:3306
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.mysql:/var/lib/mysql

  wpcli:
    image: tatemz/wp-cli
    volumes_from:
      - wordpress
    entrypoint: wp
    command: "--info"
